// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ddpoll.proto

package ddpoll

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PollStreamConfig_RankBy int32

const (
	PollStreamConfig_Time          PollStreamConfig_RankBy = 0
	PollStreamConfig_Participation PollStreamConfig_RankBy = 1
	PollStreamConfig_Stars         PollStreamConfig_RankBy = 2
)

var PollStreamConfig_RankBy_name = map[int32]string{
	0: "Time",
	1: "Participation",
	2: "Stars",
}

var PollStreamConfig_RankBy_value = map[string]int32{
	"Time":          0,
	"Participation": 1,
	"Stars":         2,
}

func (x PollStreamConfig_RankBy) String() string {
	return proto.EnumName(PollStreamConfig_RankBy_name, int32(x))
}

func (PollStreamConfig_RankBy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{2, 0}
}

type AuthQuery struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthQuery) Reset()         { *m = AuthQuery{} }
func (m *AuthQuery) String() string { return proto.CompactTextString(m) }
func (*AuthQuery) ProtoMessage()    {}
func (*AuthQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{0}
}

func (m *AuthQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthQuery.Unmarshal(m, b)
}
func (m *AuthQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthQuery.Marshal(b, m, deterministic)
}
func (m *AuthQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthQuery.Merge(m, src)
}
func (m *AuthQuery) XXX_Size() int {
	return xxx_messageInfo_AuthQuery.Size(m)
}
func (m *AuthQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthQuery.DiscardUnknown(m)
}

var xxx_messageInfo_AuthQuery proto.InternalMessageInfo

func (m *AuthQuery) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AuthQuery) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResp) Reset()         { *m = AuthResp{} }
func (m *AuthResp) String() string { return proto.CompactTextString(m) }
func (*AuthResp) ProtoMessage()    {}
func (*AuthResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{1}
}

func (m *AuthResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResp.Unmarshal(m, b)
}
func (m *AuthResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResp.Marshal(b, m, deterministic)
}
func (m *AuthResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResp.Merge(m, src)
}
func (m *AuthResp) XXX_Size() int {
	return xxx_messageInfo_AuthResp.Size(m)
}
func (m *AuthResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResp proto.InternalMessageInfo

func (m *AuthResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type PollStreamConfig struct {
	ShowVoted            bool                    `protobuf:"varint,1,opt,name=showVoted,proto3" json:"showVoted,omitempty"`
	RankBy               PollStreamConfig_RankBy `protobuf:"varint,2,opt,name=rankBy,proto3,enum=ddpoll.PollStreamConfig_RankBy" json:"rankBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PollStreamConfig) Reset()         { *m = PollStreamConfig{} }
func (m *PollStreamConfig) String() string { return proto.CompactTextString(m) }
func (*PollStreamConfig) ProtoMessage()    {}
func (*PollStreamConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{2}
}

func (m *PollStreamConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollStreamConfig.Unmarshal(m, b)
}
func (m *PollStreamConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollStreamConfig.Marshal(b, m, deterministic)
}
func (m *PollStreamConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollStreamConfig.Merge(m, src)
}
func (m *PollStreamConfig) XXX_Size() int {
	return xxx_messageInfo_PollStreamConfig.Size(m)
}
func (m *PollStreamConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PollStreamConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PollStreamConfig proto.InternalMessageInfo

func (m *PollStreamConfig) GetShowVoted() bool {
	if m != nil {
		return m.ShowVoted
	}
	return false
}

func (m *PollStreamConfig) GetRankBy() PollStreamConfig_RankBy {
	if m != nil {
		return m.RankBy
	}
	return PollStreamConfig_Time
}

type Poll struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Tags                 []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Options              []string `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Poll) Reset()         { *m = Poll{} }
func (m *Poll) String() string { return proto.CompactTextString(m) }
func (*Poll) ProtoMessage()    {}
func (*Poll) Descriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{3}
}

func (m *Poll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Poll.Unmarshal(m, b)
}
func (m *Poll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Poll.Marshal(b, m, deterministic)
}
func (m *Poll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Poll.Merge(m, src)
}
func (m *Poll) XXX_Size() int {
	return xxx_messageInfo_Poll.Size(m)
}
func (m *Poll) XXX_DiscardUnknown() {
	xxx_messageInfo_Poll.DiscardUnknown(m)
}

var xxx_messageInfo_Poll proto.InternalMessageInfo

func (m *Poll) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Poll) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Poll) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Poll) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Poll) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

func init() {
	proto.RegisterEnum("ddpoll.PollStreamConfig_RankBy", PollStreamConfig_RankBy_name, PollStreamConfig_RankBy_value)
	proto.RegisterType((*AuthQuery)(nil), "ddpoll.AuthQuery")
	proto.RegisterType((*AuthResp)(nil), "ddpoll.AuthResp")
	proto.RegisterType((*PollStreamConfig)(nil), "ddpoll.PollStreamConfig")
	proto.RegisterType((*Poll)(nil), "ddpoll.Poll")
}

func init() {
	proto.RegisterFile("ddpoll.proto", fileDescriptor_907ccde7d6668e21)
}

var fileDescriptor_907ccde7d6668e21 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4d, 0x4f, 0xea, 0x40,
	0x14, 0x86, 0x69, 0x69, 0x7b, 0xdb, 0x13, 0x2e, 0x29, 0xe7, 0xde, 0x98, 0x09, 0x31, 0x91, 0xcc,
	0xca, 0x15, 0x21, 0x18, 0xe3, 0xc2, 0x15, 0x8a, 0x7b, 0x2c, 0xc6, 0xfd, 0x40, 0x47, 0x98, 0x58,
	0x3a, 0xcd, 0xcc, 0x20, 0x61, 0xeb, 0xdf, 0xf0, 0xcf, 0x9a, 0x99, 0x96, 0x8f, 0x98, 0xb8, 0x3b,
	0xef, 0xdb, 0xf3, 0xf9, 0x74, 0xa0, 0x93, 0xe7, 0x95, 0x2c, 0x8a, 0x61, 0xa5, 0xa4, 0x91, 0x18,
	0xd5, 0x8a, 0xde, 0x43, 0x32, 0xd9, 0x9a, 0xf5, 0xf3, 0x96, 0xab, 0x3d, 0x22, 0x04, 0x25, 0xdb,
	0x70, 0xe2, 0x0d, 0xbc, 0xeb, 0x24, 0x73, 0x31, 0xf6, 0x21, 0xae, 0x98, 0xd6, 0x3b, 0xa9, 0x72,
	0xe2, 0x3b, 0xff, 0xa8, 0x29, 0x85, 0xd8, 0x16, 0x67, 0x5c, 0x57, 0x78, 0x01, 0x91, 0x36, 0xcc,
	0x6c, 0xb5, 0xab, 0x0e, 0xb3, 0x46, 0xd1, 0x2f, 0x0f, 0xd2, 0x99, 0x2c, 0x8a, 0xb9, 0x51, 0x9c,
	0x6d, 0x1e, 0x65, 0xf9, 0x26, 0x56, 0x78, 0x09, 0x89, 0x5e, 0xcb, 0xdd, 0xab, 0x34, 0x3c, 0x77,
	0xf9, 0x71, 0x76, 0x32, 0xf0, 0x0e, 0x22, 0xc5, 0xca, 0xf7, 0x87, 0xbd, 0x1b, 0xd8, 0x1d, 0x5f,
	0x0d, 0x9b, 0xd5, 0x7f, 0xf6, 0x19, 0x66, 0x2e, 0x2d, 0x6b, 0xd2, 0xe9, 0x08, 0xa2, 0xda, 0xc1,
	0x18, 0x82, 0x17, 0xb1, 0xe1, 0x69, 0x0b, 0x7b, 0xf0, 0x77, 0xc6, 0x94, 0x11, 0x4b, 0x51, 0x31,
	0x23, 0x64, 0x99, 0x7a, 0x98, 0x40, 0x38, 0x37, 0x4c, 0xe9, 0xd4, 0xa7, 0x1f, 0x10, 0xd8, 0xa6,
	0xd8, 0x05, 0x5f, 0xe4, 0xcd, 0xe6, 0xbe, 0xc8, 0xf1, 0x3f, 0x84, 0x72, 0x57, 0x72, 0xd5, 0x9c,
	0x5c, 0x0b, 0xcb, 0x62, 0xc9, 0x0c, 0x5f, 0x49, 0xb5, 0x27, 0xed, 0x9a, 0xc5, 0x41, 0x5b, 0x76,
	0x86, 0xad, 0x34, 0x09, 0x06, 0x6d, 0xcb, 0xce, 0xc6, 0x48, 0xe0, 0x8f, 0xac, 0xec, 0x50, 0x4d,
	0x42, 0x67, 0x1f, 0xe4, 0xf8, 0xd3, 0x83, 0x68, 0x3a, 0x75, 0xa3, 0x6f, 0xa1, 0x63, 0x21, 0xf2,
	0xd2, 0x08, 0xdb, 0x0c, 0x7b, 0x87, 0x6b, 0x8f, 0xff, 0xa5, 0x9f, 0x9e, 0x5b, 0x96, 0x36, 0x6d,
	0xe1, 0x04, 0xfe, 0x3d, 0x69, 0xc3, 0x16, 0x85, 0xd0, 0xeb, 0x13, 0x17, 0x24, 0xbf, 0xb1, 0xea,
	0x77, 0xce, 0xbf, 0xd0, 0xd6, 0xc8, 0x5b, 0x44, 0xee, 0x29, 0xdc, 0x7c, 0x07, 0x00, 0x00, 0xff,
	0xff, 0xd8, 0x33, 0x65, 0x8f, 0x1a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DDPollClient is the client API for DDPoll service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DDPollClient interface {
	Authenticate(ctx context.Context, in *AuthQuery, opts ...grpc.CallOption) (*AuthResp, error)
	EstablishPollStream(ctx context.Context, in *PollStreamConfig, opts ...grpc.CallOption) (DDPoll_EstablishPollStreamClient, error)
}

type dDPollClient struct {
	cc grpc.ClientConnInterface
}

func NewDDPollClient(cc grpc.ClientConnInterface) DDPollClient {
	return &dDPollClient{cc}
}

func (c *dDPollClient) Authenticate(ctx context.Context, in *AuthQuery, opts ...grpc.CallOption) (*AuthResp, error) {
	out := new(AuthResp)
	err := c.cc.Invoke(ctx, "/ddpoll.DDPoll/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dDPollClient) EstablishPollStream(ctx context.Context, in *PollStreamConfig, opts ...grpc.CallOption) (DDPoll_EstablishPollStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DDPoll_serviceDesc.Streams[0], "/ddpoll.DDPoll/EstablishPollStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &dDPollEstablishPollStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DDPoll_EstablishPollStreamClient interface {
	Recv() (*Poll, error)
	grpc.ClientStream
}

type dDPollEstablishPollStreamClient struct {
	grpc.ClientStream
}

func (x *dDPollEstablishPollStreamClient) Recv() (*Poll, error) {
	m := new(Poll)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DDPollServer is the server API for DDPoll service.
type DDPollServer interface {
	Authenticate(context.Context, *AuthQuery) (*AuthResp, error)
	EstablishPollStream(*PollStreamConfig, DDPoll_EstablishPollStreamServer) error
}

// UnimplementedDDPollServer can be embedded to have forward compatible implementations.
type UnimplementedDDPollServer struct {
}

func (*UnimplementedDDPollServer) Authenticate(ctx context.Context, req *AuthQuery) (*AuthResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (*UnimplementedDDPollServer) EstablishPollStream(req *PollStreamConfig, srv DDPoll_EstablishPollStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method EstablishPollStream not implemented")
}

func RegisterDDPollServer(s *grpc.Server, srv DDPollServer) {
	s.RegisterService(&_DDPoll_serviceDesc, srv)
}

func _DDPoll_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DDPollServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ddpoll.DDPoll/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DDPollServer).Authenticate(ctx, req.(*AuthQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _DDPoll_EstablishPollStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PollStreamConfig)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DDPollServer).EstablishPollStream(m, &dDPollEstablishPollStreamServer{stream})
}

type DDPoll_EstablishPollStreamServer interface {
	Send(*Poll) error
	grpc.ServerStream
}

type dDPollEstablishPollStreamServer struct {
	grpc.ServerStream
}

func (x *dDPollEstablishPollStreamServer) Send(m *Poll) error {
	return x.ServerStream.SendMsg(m)
}

var _DDPoll_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ddpoll.DDPoll",
	HandlerType: (*DDPollServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _DDPoll_Authenticate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EstablishPollStream",
			Handler:       _DDPoll_EstablishPollStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ddpoll.proto",
}
