// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ddpoll.proto

package ddpoll

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Next_PollControl int32

const (
	Next_foward         Next_PollControl = 0
	Next_backward       Next_PollControl = 1
	Next_start          Next_PollControl = 3
	Next_stop           Next_PollControl = 4
	Next_terminateGroup Next_PollControl = 5
)

var Next_PollControl_name = map[int32]string{
	0: "foward",
	1: "backward",
	3: "start",
	4: "stop",
	5: "terminateGroup",
}

var Next_PollControl_value = map[string]int32{
	"foward":         0,
	"backward":       1,
	"start":          3,
	"stop":           4,
	"terminateGroup": 5,
}

func (x Next_PollControl) String() string {
	return proto.EnumName(Next_PollControl_name, int32(x))
}

func (Next_PollControl) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{0, 0}
}

type PollStreamConfig_RankBy int32

const (
	PollStreamConfig_Time          PollStreamConfig_RankBy = 0
	PollStreamConfig_Participation PollStreamConfig_RankBy = 1
	PollStreamConfig_Stars         PollStreamConfig_RankBy = 2
)

var PollStreamConfig_RankBy_name = map[int32]string{
	0: "Time",
	1: "Participation",
	2: "Stars",
}

var PollStreamConfig_RankBy_value = map[string]int32{
	"Time":          0,
	"Participation": 1,
	"Stars":         2,
}

func (x PollStreamConfig_RankBy) String() string {
	return proto.EnumName(PollStreamConfig_RankBy_name, int32(x))
}

func (PollStreamConfig_RankBy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{2, 0}
}

type Poll_DisplayType int32

const (
	Poll_OnVote   Poll_DisplayType = 0
	Poll_OnReveal Poll_DisplayType = 1
)

var Poll_DisplayType_name = map[int32]string{
	0: "OnVote",
	1: "OnReveal",
}

var Poll_DisplayType_value = map[string]int32{
	"OnVote":   0,
	"OnReveal": 1,
}

func (x Poll_DisplayType) String() string {
	return proto.EnumName(Poll_DisplayType_name, int32(x))
}

func (Poll_DisplayType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{3, 0}
}

type UserAction_Action int32

const (
	UserAction_Unknown        UserAction_Action = 0
	UserAction_Authenticate   UserAction_Action = 1
	UserAction_VoteMultiple   UserAction_Action = 2
	UserAction_Star           UserAction_Action = 3
	UserAction_Reveal         UserAction_Action = 4
	UserAction_Create         UserAction_Action = 5
	UserAction_Registeration  UserAction_Action = 6
	UserAction_GroupPolls     UserAction_Action = 7
	UserAction_StartGroupPoll UserAction_Action = 8
	UserAction_StopGroupPoll  UserAction_Action = 9
)

var UserAction_Action_name = map[int32]string{
	0: "Unknown",
	1: "Authenticate",
	2: "VoteMultiple",
	3: "Star",
	4: "Reveal",
	5: "Create",
	6: "Registeration",
	7: "GroupPolls",
	8: "StartGroupPoll",
	9: "StopGroupPoll",
}

var UserAction_Action_value = map[string]int32{
	"Unknown":        0,
	"Authenticate":   1,
	"VoteMultiple":   2,
	"Star":           3,
	"Reveal":         4,
	"Create":         5,
	"Registeration":  6,
	"GroupPolls":     7,
	"StartGroupPoll": 8,
	"StopGroupPoll":  9,
}

func (x UserAction_Action) String() string {
	return proto.EnumName(UserAction_Action_name, int32(x))
}

func (UserAction_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{6, 0}
}

type Next struct {
	Signal               Next_PollControl `protobuf:"varint,1,opt,name=signal,proto3,enum=ddpoll.Next_PollControl" json:"signal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Next) Reset()         { *m = Next{} }
func (m *Next) String() string { return proto.CompactTextString(m) }
func (*Next) ProtoMessage()    {}
func (*Next) Descriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{0}
}

func (m *Next) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Next.Unmarshal(m, b)
}
func (m *Next) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Next.Marshal(b, m, deterministic)
}
func (m *Next) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Next.Merge(m, src)
}
func (m *Next) XXX_Size() int {
	return xxx_messageInfo_Next.Size(m)
}
func (m *Next) XXX_DiscardUnknown() {
	xxx_messageInfo_Next.DiscardUnknown(m)
}

var xxx_messageInfo_Next proto.InternalMessageInfo

func (m *Next) GetSignal() Next_PollControl {
	if m != nil {
		return m.Signal
	}
	return Next_foward
}

type JoinPollQuery struct {
	Phrase               string   `protobuf:"bytes,1,opt,name=phrase,proto3" json:"phrase,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinPollQuery) Reset()         { *m = JoinPollQuery{} }
func (m *JoinPollQuery) String() string { return proto.CompactTextString(m) }
func (*JoinPollQuery) ProtoMessage()    {}
func (*JoinPollQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{1}
}

func (m *JoinPollQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinPollQuery.Unmarshal(m, b)
}
func (m *JoinPollQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinPollQuery.Marshal(b, m, deterministic)
}
func (m *JoinPollQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinPollQuery.Merge(m, src)
}
func (m *JoinPollQuery) XXX_Size() int {
	return xxx_messageInfo_JoinPollQuery.Size(m)
}
func (m *JoinPollQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinPollQuery.DiscardUnknown(m)
}

var xxx_messageInfo_JoinPollQuery proto.InternalMessageInfo

func (m *JoinPollQuery) GetPhrase() string {
	if m != nil {
		return m.Phrase
	}
	return ""
}

func (m *JoinPollQuery) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type PollStreamConfig struct {
	RankBy               PollStreamConfig_RankBy `protobuf:"varint,1,opt,name=rankBy,proto3,enum=ddpoll.PollStreamConfig_RankBy" json:"rankBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PollStreamConfig) Reset()         { *m = PollStreamConfig{} }
func (m *PollStreamConfig) String() string { return proto.CompactTextString(m) }
func (*PollStreamConfig) ProtoMessage()    {}
func (*PollStreamConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{2}
}

func (m *PollStreamConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollStreamConfig.Unmarshal(m, b)
}
func (m *PollStreamConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollStreamConfig.Marshal(b, m, deterministic)
}
func (m *PollStreamConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollStreamConfig.Merge(m, src)
}
func (m *PollStreamConfig) XXX_Size() int {
	return xxx_messageInfo_PollStreamConfig.Size(m)
}
func (m *PollStreamConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PollStreamConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PollStreamConfig proto.InternalMessageInfo

func (m *PollStreamConfig) GetRankBy() PollStreamConfig_RankBy {
	if m != nil {
		return m.RankBy
	}
	return PollStreamConfig_Time
}

type Poll struct {
	Id                   uint64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                string           `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Category             string           `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Body                 string           `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Stars                uint64           `protobuf:"varint,5,opt,name=stars,proto3" json:"stars,omitempty"`
	DisplayType          Poll_DisplayType `protobuf:"varint,6,opt,name=displayType,proto3,enum=ddpoll.Poll_DisplayType" json:"displayType,omitempty"`
	Tags                 []string         `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Options              []string         `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty"`
	Attachment           []byte           `protobuf:"bytes,9,opt,name=attachment,proto3" json:"attachment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Poll) Reset()         { *m = Poll{} }
func (m *Poll) String() string { return proto.CompactTextString(m) }
func (*Poll) ProtoMessage()    {}
func (*Poll) Descriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{3}
}

func (m *Poll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Poll.Unmarshal(m, b)
}
func (m *Poll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Poll.Marshal(b, m, deterministic)
}
func (m *Poll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Poll.Merge(m, src)
}
func (m *Poll) XXX_Size() int {
	return xxx_messageInfo_Poll.Size(m)
}
func (m *Poll) XXX_DiscardUnknown() {
	xxx_messageInfo_Poll.DiscardUnknown(m)
}

var xxx_messageInfo_Poll proto.InternalMessageInfo

func (m *Poll) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Poll) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Poll) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Poll) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Poll) GetStars() uint64 {
	if m != nil {
		return m.Stars
	}
	return 0
}

func (m *Poll) GetDisplayType() Poll_DisplayType {
	if m != nil {
		return m.DisplayType
	}
	return Poll_OnVote
}

func (m *Poll) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Poll) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Poll) GetAttachment() []byte {
	if m != nil {
		return m.Attachment
	}
	return nil
}

type SearchQuery struct {
	PollID               uint32   `protobuf:"varint,1,opt,name=pollID,proto3" json:"pollID,omitempty"`
	Keywords             string   `protobuf:"bytes,2,opt,name=keywords,proto3" json:"keywords,omitempty"`
	Tags                 string   `protobuf:"bytes,3,opt,name=tags,proto3" json:"tags,omitempty"`
	NumResultsMax        uint32   `protobuf:"varint,4,opt,name=numResultsMax,proto3" json:"numResultsMax,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchQuery) Reset()         { *m = SearchQuery{} }
func (m *SearchQuery) String() string { return proto.CompactTextString(m) }
func (*SearchQuery) ProtoMessage()    {}
func (*SearchQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{4}
}

func (m *SearchQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchQuery.Unmarshal(m, b)
}
func (m *SearchQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchQuery.Marshal(b, m, deterministic)
}
func (m *SearchQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchQuery.Merge(m, src)
}
func (m *SearchQuery) XXX_Size() int {
	return xxx_messageInfo_SearchQuery.Size(m)
}
func (m *SearchQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchQuery.DiscardUnknown(m)
}

var xxx_messageInfo_SearchQuery proto.InternalMessageInfo

func (m *SearchQuery) GetPollID() uint32 {
	if m != nil {
		return m.PollID
	}
	return 0
}

func (m *SearchQuery) GetKeywords() string {
	if m != nil {
		return m.Keywords
	}
	return ""
}

func (m *SearchQuery) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *SearchQuery) GetNumResultsMax() uint32 {
	if m != nil {
		return m.NumResultsMax
	}
	return 0
}

type SearchResp struct {
	NumResultsActual     uint32   `protobuf:"varint,1,opt,name=numResultsActual,proto3" json:"numResultsActual,omitempty"`
	Polls                []*Poll  `protobuf:"bytes,2,rep,name=polls,proto3" json:"polls,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResp) Reset()         { *m = SearchResp{} }
func (m *SearchResp) String() string { return proto.CompactTextString(m) }
func (*SearchResp) ProtoMessage()    {}
func (*SearchResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{5}
}

func (m *SearchResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResp.Unmarshal(m, b)
}
func (m *SearchResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResp.Marshal(b, m, deterministic)
}
func (m *SearchResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResp.Merge(m, src)
}
func (m *SearchResp) XXX_Size() int {
	return xxx_messageInfo_SearchResp.Size(m)
}
func (m *SearchResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResp.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResp proto.InternalMessageInfo

func (m *SearchResp) GetNumResultsActual() uint32 {
	if m != nil {
		return m.NumResultsActual
	}
	return 0
}

func (m *SearchResp) GetPolls() []*Poll {
	if m != nil {
		return m.Polls
	}
	return nil
}

type UserAction struct {
	Header               *UserAction_Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ResourceID           uint32             `protobuf:"varint,2,opt,name=resourceID,proto3" json:"resourceID,omitempty"`
	Action               UserAction_Action  `protobuf:"varint,3,opt,name=action,proto3,enum=ddpoll.UserAction_Action" json:"action,omitempty"`
	Parameters           []string           `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UserAction) Reset()         { *m = UserAction{} }
func (m *UserAction) String() string { return proto.CompactTextString(m) }
func (*UserAction) ProtoMessage()    {}
func (*UserAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{6}
}

func (m *UserAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAction.Unmarshal(m, b)
}
func (m *UserAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAction.Marshal(b, m, deterministic)
}
func (m *UserAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAction.Merge(m, src)
}
func (m *UserAction) XXX_Size() int {
	return xxx_messageInfo_UserAction.Size(m)
}
func (m *UserAction) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAction.DiscardUnknown(m)
}

var xxx_messageInfo_UserAction proto.InternalMessageInfo

func (m *UserAction) GetHeader() *UserAction_Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UserAction) GetResourceID() uint32 {
	if m != nil {
		return m.ResourceID
	}
	return 0
}

func (m *UserAction) GetAction() UserAction_Action {
	if m != nil {
		return m.Action
	}
	return UserAction_Unknown
}

func (m *UserAction) GetParameters() []string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type UserAction_Header struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token                uint64   `protobuf:"varint,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAction_Header) Reset()         { *m = UserAction_Header{} }
func (m *UserAction_Header) String() string { return proto.CompactTextString(m) }
func (*UserAction_Header) ProtoMessage()    {}
func (*UserAction_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{6, 0}
}

func (m *UserAction_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAction_Header.Unmarshal(m, b)
}
func (m *UserAction_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAction_Header.Marshal(b, m, deterministic)
}
func (m *UserAction_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAction_Header.Merge(m, src)
}
func (m *UserAction_Header) XXX_Size() int {
	return xxx_messageInfo_UserAction_Header.Size(m)
}
func (m *UserAction_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAction_Header.DiscardUnknown(m)
}

var xxx_messageInfo_UserAction_Header proto.InternalMessageInfo

func (m *UserAction_Header) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserAction_Header) GetToken() uint64 {
	if m != nil {
		return m.Token
	}
	return 0
}

type ActionSummary struct {
	Info                 []byte   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Token                uint64   `protobuf:"varint,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionSummary) Reset()         { *m = ActionSummary{} }
func (m *ActionSummary) String() string { return proto.CompactTextString(m) }
func (*ActionSummary) ProtoMessage()    {}
func (*ActionSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_907ccde7d6668e21, []int{7}
}

func (m *ActionSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionSummary.Unmarshal(m, b)
}
func (m *ActionSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionSummary.Marshal(b, m, deterministic)
}
func (m *ActionSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionSummary.Merge(m, src)
}
func (m *ActionSummary) XXX_Size() int {
	return xxx_messageInfo_ActionSummary.Size(m)
}
func (m *ActionSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionSummary.DiscardUnknown(m)
}

var xxx_messageInfo_ActionSummary proto.InternalMessageInfo

func (m *ActionSummary) GetInfo() []byte {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ActionSummary) GetToken() uint64 {
	if m != nil {
		return m.Token
	}
	return 0
}

func init() {
	proto.RegisterEnum("ddpoll.Next_PollControl", Next_PollControl_name, Next_PollControl_value)
	proto.RegisterEnum("ddpoll.PollStreamConfig_RankBy", PollStreamConfig_RankBy_name, PollStreamConfig_RankBy_value)
	proto.RegisterEnum("ddpoll.Poll_DisplayType", Poll_DisplayType_name, Poll_DisplayType_value)
	proto.RegisterEnum("ddpoll.UserAction_Action", UserAction_Action_name, UserAction_Action_value)
	proto.RegisterType((*Next)(nil), "ddpoll.Next")
	proto.RegisterType((*JoinPollQuery)(nil), "ddpoll.JoinPollQuery")
	proto.RegisterType((*PollStreamConfig)(nil), "ddpoll.PollStreamConfig")
	proto.RegisterType((*Poll)(nil), "ddpoll.Poll")
	proto.RegisterType((*SearchQuery)(nil), "ddpoll.SearchQuery")
	proto.RegisterType((*SearchResp)(nil), "ddpoll.SearchResp")
	proto.RegisterType((*UserAction)(nil), "ddpoll.UserAction")
	proto.RegisterType((*UserAction_Header)(nil), "ddpoll.UserAction.Header")
	proto.RegisterType((*ActionSummary)(nil), "ddpoll.ActionSummary")
}

func init() {
	proto.RegisterFile("ddpoll.proto", fileDescriptor_907ccde7d6668e21)
}

var fileDescriptor_907ccde7d6668e21 = []byte{
	// 858 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xdb, 0x8e, 0xdb, 0x36,
	0x13, 0xf6, 0x41, 0xd6, 0x7a, 0xc7, 0x07, 0x28, 0xcc, 0x9f, 0x1f, 0xaa, 0x2f, 0xda, 0x85, 0x50,
	0xa0, 0x8b, 0x5e, 0x18, 0xdb, 0xed, 0x45, 0xda, 0x5c, 0x14, 0xd8, 0xd8, 0x3d, 0x6c, 0x8b, 0x24,
	0x5b, 0x3a, 0x69, 0x6f, 0x7a, 0xc3, 0xb5, 0x66, 0x6d, 0xc2, 0x32, 0x29, 0x90, 0x54, 0x37, 0x42,
	0xd1, 0x17, 0xe8, 0x03, 0xf4, 0x0d, 0xf2, 0x24, 0x7d, 0xb1, 0x62, 0x28, 0xd9, 0x96, 0x9b, 0x2d,
	0xd0, 0x2b, 0x71, 0x3e, 0x0e, 0x87, 0xf3, 0x7d, 0x9c, 0x19, 0xc1, 0x30, 0x4d, 0x73, 0x9d, 0x65,
	0xd3, 0xdc, 0x68, 0xa7, 0x59, 0x58, 0x59, 0xc9, 0x1f, 0x6d, 0x08, 0x5e, 0xe2, 0x5b, 0xc7, 0x2e,
	0x20, 0xb4, 0x72, 0xa5, 0x44, 0x16, 0xb7, 0xcf, 0xda, 0xe7, 0xe3, 0xcb, 0x78, 0x5a, 0xfb, 0xd3,
	0xee, 0xf4, 0x46, 0x67, 0xd9, 0x4c, 0x2b, 0x67, 0x74, 0xc6, 0x6b, 0xbf, 0xe4, 0x06, 0x06, 0x0d,
	0x98, 0x01, 0x84, 0x77, 0xfa, 0x5e, 0x98, 0x34, 0x6a, 0xb1, 0x21, 0xf4, 0x6f, 0xc5, 0x72, 0xe3,
	0xad, 0x36, 0x3b, 0x85, 0x9e, 0x75, 0xc2, 0xb8, 0xa8, 0xcb, 0xfa, 0x10, 0x58, 0xa7, 0xf3, 0x28,
	0x60, 0x0c, 0xc6, 0x0e, 0xcd, 0x56, 0x2a, 0xe1, 0xf0, 0x5b, 0xa3, 0x8b, 0x3c, 0xea, 0x25, 0xd7,
	0x30, 0xfa, 0x5e, 0x4b, 0x45, 0x51, 0x7f, 0x2c, 0xd0, 0x94, 0xec, 0xff, 0x10, 0xe6, 0x6b, 0x23,
	0x2c, 0xfa, 0xa4, 0x4e, 0x79, 0x6d, 0xb1, 0x33, 0x18, 0xa4, 0xd2, 0xe6, 0x99, 0x28, 0x5f, 0x8a,
	0x2d, 0xc6, 0x1d, 0xbf, 0xd9, 0x84, 0x92, 0xdf, 0x21, 0xa2, 0x30, 0x0b, 0x67, 0x50, 0x6c, 0x67,
	0x5a, 0xdd, 0xc9, 0x15, 0x7b, 0x0a, 0xa1, 0x11, 0x6a, 0xf3, 0xbc, 0xac, 0x29, 0x7e, 0xb4, 0xa3,
	0xf8, 0x4f, 0xcf, 0x29, 0xf7, 0x6e, 0xbc, 0x76, 0x4f, 0x2e, 0x20, 0xac, 0x10, 0xca, 0xff, 0xb5,
	0xdc, 0x62, 0xd4, 0x62, 0x8f, 0x60, 0x74, 0x23, 0x8c, 0x93, 0x4b, 0x99, 0x0b, 0x27, 0xb5, 0xaa,
	0x78, 0x2e, 0x9c, 0x30, 0x36, 0xea, 0x24, 0xef, 0x3a, 0x10, 0x50, 0x54, 0x36, 0x86, 0x8e, 0x4c,
	0xfd, 0x7d, 0x01, 0xef, 0xc8, 0x94, 0xfd, 0x0f, 0x7a, 0xfa, 0x5e, 0xa1, 0xa9, 0x73, 0xae, 0x0c,
	0x36, 0x81, 0xfe, 0x52, 0x38, 0x5c, 0x69, 0x53, 0xc6, 0x5d, 0xbf, 0xb1, 0xb7, 0x19, 0x83, 0xe0,
	0x56, 0xa7, 0x65, 0x1c, 0x78, 0xdc, 0xaf, 0x29, 0x0a, 0x29, 0x6a, 0xe3, 0x9e, 0x0f, 0x5c, 0x19,
	0xec, 0xd9, 0x5e, 0x95, 0xd7, 0x65, 0x8e, 0x71, 0x78, 0xfc, 0x8e, 0x94, 0xce, 0x74, 0x7e, 0xd8,
	0xe7, 0x4d, 0x67, 0xba, 0xc5, 0x89, 0x95, 0x8d, 0x4f, 0xce, 0xba, 0x74, 0x0b, 0xad, 0x59, 0x0c,
	0x27, 0x3a, 0x27, 0x6e, 0x36, 0xee, 0x7b, 0x78, 0x67, 0xb2, 0x0f, 0x01, 0x84, 0x73, 0x62, 0xb9,
	0xde, 0xa2, 0x72, 0xf1, 0xe9, 0x59, 0xfb, 0x7c, 0xc8, 0x1b, 0x48, 0xf2, 0x09, 0x0c, 0x1a, 0x37,
	0x51, 0x69, 0xbc, 0x52, 0x3f, 0x69, 0x87, 0x55, 0x69, 0xbc, 0x52, 0x1c, 0x7f, 0x45, 0x91, 0x45,
	0xed, 0xe4, 0x37, 0x18, 0x2c, 0x50, 0x98, 0xe5, 0xfa, 0xf0, 0xde, 0x3a, 0xcb, 0xae, 0xe7, 0x5e,
	0xb1, 0x11, 0xaf, 0x2d, 0xd2, 0x67, 0x83, 0xe5, 0xbd, 0x36, 0xa9, 0xad, 0x85, 0xdb, 0xdb, 0xfb,
	0xcc, 0x2b, 0xdd, 0xaa, 0xcc, 0x3f, 0x86, 0x91, 0x2a, 0xb6, 0x1c, 0x6d, 0x91, 0x39, 0xfb, 0x42,
	0xbc, 0xf5, 0xe2, 0x8d, 0xf8, 0x31, 0x98, 0xfc, 0x02, 0x50, 0x5d, 0xce, 0xd1, 0xe6, 0xec, 0x53,
	0x88, 0x0e, 0xdb, 0x57, 0x4b, 0x57, 0xd4, 0xad, 0x30, 0xe2, 0xef, 0xe1, 0x2c, 0x81, 0x1e, 0x65,
	0x46, 0xc9, 0x74, 0xcf, 0x07, 0x97, 0xc3, 0xa6, 0xc6, 0xbc, 0xda, 0x4a, 0xfe, 0xec, 0x02, 0xbc,
	0xb1, 0x68, 0xae, 0x96, 0xa4, 0x19, 0xfb, 0x0c, 0xc2, 0x35, 0x8a, 0x14, 0x8d, 0x0f, 0x3a, 0xb8,
	0xfc, 0x60, 0x77, 0xe6, 0xe0, 0x33, 0xfd, 0xce, 0x3b, 0xf0, 0xda, 0x91, 0x54, 0x36, 0x68, 0x75,
	0x61, 0x96, 0x78, 0x3d, 0xf7, 0xbc, 0x47, 0xbc, 0x81, 0x50, 0x48, 0xe1, 0x0f, 0x7a, 0xee, 0xe3,
	0x07, 0x43, 0x56, 0x1f, 0x5e, 0x3b, 0x52, 0xc8, 0x5c, 0x18, 0xb1, 0x45, 0x87, 0xc6, 0xc6, 0x81,
	0x7f, 0xd5, 0x06, 0x32, 0x79, 0x06, 0x61, 0x95, 0x04, 0x49, 0x5e, 0x58, 0x34, 0x8a, 0xfa, 0xab,
	0x6a, 0xbe, 0xbd, 0x4d, 0xe5, 0xe7, 0xf4, 0x06, 0x95, 0xcf, 0x29, 0xe0, 0x95, 0x91, 0xbc, 0x6b,
	0x43, 0x58, 0x93, 0x1d, 0xc0, 0xc9, 0x1b, 0xb5, 0x51, 0xfa, 0x5e, 0x45, 0x2d, 0x16, 0xc1, 0xf0,
	0xaa, 0x70, 0x6b, 0x54, 0x4e, 0x52, 0x51, 0x47, 0x6d, 0x42, 0xa8, 0x1a, 0x5e, 0x14, 0x99, 0x93,
	0x79, 0x86, 0x51, 0x87, 0xfa, 0x8a, 0x5a, 0x27, 0xea, 0x52, 0xad, 0xd4, 0xd5, 0x11, 0xd0, 0x7a,
	0x66, 0x90, 0xce, 0xf4, 0xa8, 0xdf, 0x38, 0xae, 0xa4, 0x75, 0x68, 0xaa, 0x7e, 0x0b, 0xd9, 0x18,
	0xc0, 0x4f, 0x0e, 0x52, 0xdd, 0x46, 0x27, 0x34, 0x52, 0x28, 0x88, 0xdb, 0x83, 0x51, 0x9f, 0x8e,
	0x2d, 0x9c, 0xce, 0x0f, 0xd0, 0x69, 0xf2, 0x25, 0x8c, 0xaa, 0x34, 0x17, 0xc5, 0x76, 0x2b, 0xaa,
	0x0e, 0x93, 0xea, 0x4e, 0x7b, 0x9a, 0x43, 0xee, 0xd7, 0x0f, 0x53, 0xbc, 0xfc, 0xab, 0x03, 0xe1,
	0x7c, 0xee, 0x1b, 0xfb, 0x0a, 0x1e, 0x7f, 0x6d, 0x9d, 0xb8, 0xcd, 0xa4, 0x5d, 0x1f, 0xe6, 0x07,
	0x8b, 0xff, 0x6d, 0xa6, 0x4c, 0x8e, 0x8a, 0x24, 0x69, 0x5d, 0xb4, 0xd9, 0x57, 0xf0, 0xe8, 0x1b,
	0xa9, 0x52, 0xb2, 0x9f, 0x97, 0x3f, 0x60, 0xf9, 0xb3, 0x36, 0x29, 0x7b, 0xbc, 0x73, 0x6b, 0xf4,
	0xc5, 0x84, 0x1d, 0x83, 0x54, 0xaf, 0x49, 0x8b, 0x3d, 0x85, 0xfe, 0x5c, 0xd7, 0x8a, 0xb3, 0xf7,
	0xdf, 0x7e, 0xf2, 0x64, 0x87, 0x1d, 0xd1, 0x4d, 0x5a, 0xec, 0x8b, 0xc3, 0x9c, 0xf5, 0xc2, 0xb0,
	0xbd, 0xe7, 0xd1, 0xf8, 0x7d, 0x20, 0xe5, 0x19, 0x3c, 0xd9, 0xb3, 0x9e, 0x65, 0x12, 0x95, 0xfb,
	0xef, 0xbc, 0xe9, 0x47, 0x42, 0x41, 0x6e, 0x43, 0xff, 0x0b, 0xfa, 0xfc, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xef, 0x5d, 0xa8, 0x62, 0x92, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DDPollClient is the client API for DDPoll service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DDPollClient interface {
	EstablishPollStream(ctx context.Context, in *PollStreamConfig, opts ...grpc.CallOption) (DDPoll_EstablishPollStreamClient, error)
	FindPollByKeyWord(ctx context.Context, in *SearchQuery, opts ...grpc.CallOption) (*SearchResp, error)
	DoAction(ctx context.Context, in *UserAction, opts ...grpc.CallOption) (*ActionSummary, error)
	JoinPollGroup(ctx context.Context, in *JoinPollQuery, opts ...grpc.CallOption) (DDPoll_JoinPollGroupClient, error)
	EstablishClientStream(ctx context.Context, in *PollStreamConfig, opts ...grpc.CallOption) (DDPoll_EstablishClientStreamClient, error)
}

type dDPollClient struct {
	cc grpc.ClientConnInterface
}

func NewDDPollClient(cc grpc.ClientConnInterface) DDPollClient {
	return &dDPollClient{cc}
}

func (c *dDPollClient) EstablishPollStream(ctx context.Context, in *PollStreamConfig, opts ...grpc.CallOption) (DDPoll_EstablishPollStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DDPoll_serviceDesc.Streams[0], "/ddpoll.DDPoll/EstablishPollStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &dDPollEstablishPollStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DDPoll_EstablishPollStreamClient interface {
	Recv() (*Poll, error)
	grpc.ClientStream
}

type dDPollEstablishPollStreamClient struct {
	grpc.ClientStream
}

func (x *dDPollEstablishPollStreamClient) Recv() (*Poll, error) {
	m := new(Poll)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dDPollClient) FindPollByKeyWord(ctx context.Context, in *SearchQuery, opts ...grpc.CallOption) (*SearchResp, error) {
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, "/ddpoll.DDPoll/FindPollByKeyWord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dDPollClient) DoAction(ctx context.Context, in *UserAction, opts ...grpc.CallOption) (*ActionSummary, error) {
	out := new(ActionSummary)
	err := c.cc.Invoke(ctx, "/ddpoll.DDPoll/DoAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dDPollClient) JoinPollGroup(ctx context.Context, in *JoinPollQuery, opts ...grpc.CallOption) (DDPoll_JoinPollGroupClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DDPoll_serviceDesc.Streams[1], "/ddpoll.DDPoll/JoinPollGroup", opts...)
	if err != nil {
		return nil, err
	}
	x := &dDPollJoinPollGroupClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DDPoll_JoinPollGroupClient interface {
	Recv() (*Poll, error)
	grpc.ClientStream
}

type dDPollJoinPollGroupClient struct {
	grpc.ClientStream
}

func (x *dDPollJoinPollGroupClient) Recv() (*Poll, error) {
	m := new(Poll)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dDPollClient) EstablishClientStream(ctx context.Context, in *PollStreamConfig, opts ...grpc.CallOption) (DDPoll_EstablishClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DDPoll_serviceDesc.Streams[2], "/ddpoll.DDPoll/EstablishClientStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &dDPollEstablishClientStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DDPoll_EstablishClientStreamClient interface {
	Recv() (*Next, error)
	grpc.ClientStream
}

type dDPollEstablishClientStreamClient struct {
	grpc.ClientStream
}

func (x *dDPollEstablishClientStreamClient) Recv() (*Next, error) {
	m := new(Next)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DDPollServer is the server API for DDPoll service.
type DDPollServer interface {
	EstablishPollStream(*PollStreamConfig, DDPoll_EstablishPollStreamServer) error
	FindPollByKeyWord(context.Context, *SearchQuery) (*SearchResp, error)
	DoAction(context.Context, *UserAction) (*ActionSummary, error)
	JoinPollGroup(*JoinPollQuery, DDPoll_JoinPollGroupServer) error
	EstablishClientStream(*PollStreamConfig, DDPoll_EstablishClientStreamServer) error
}

// UnimplementedDDPollServer can be embedded to have forward compatible implementations.
type UnimplementedDDPollServer struct {
}

func (*UnimplementedDDPollServer) EstablishPollStream(req *PollStreamConfig, srv DDPoll_EstablishPollStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method EstablishPollStream not implemented")
}
func (*UnimplementedDDPollServer) FindPollByKeyWord(ctx context.Context, req *SearchQuery) (*SearchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindPollByKeyWord not implemented")
}
func (*UnimplementedDDPollServer) DoAction(ctx context.Context, req *UserAction) (*ActionSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoAction not implemented")
}
func (*UnimplementedDDPollServer) JoinPollGroup(req *JoinPollQuery, srv DDPoll_JoinPollGroupServer) error {
	return status.Errorf(codes.Unimplemented, "method JoinPollGroup not implemented")
}
func (*UnimplementedDDPollServer) EstablishClientStream(req *PollStreamConfig, srv DDPoll_EstablishClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method EstablishClientStream not implemented")
}

func RegisterDDPollServer(s *grpc.Server, srv DDPollServer) {
	s.RegisterService(&_DDPoll_serviceDesc, srv)
}

func _DDPoll_EstablishPollStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PollStreamConfig)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DDPollServer).EstablishPollStream(m, &dDPollEstablishPollStreamServer{stream})
}

type DDPoll_EstablishPollStreamServer interface {
	Send(*Poll) error
	grpc.ServerStream
}

type dDPollEstablishPollStreamServer struct {
	grpc.ServerStream
}

func (x *dDPollEstablishPollStreamServer) Send(m *Poll) error {
	return x.ServerStream.SendMsg(m)
}

func _DDPoll_FindPollByKeyWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DDPollServer).FindPollByKeyWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ddpoll.DDPoll/FindPollByKeyWord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DDPollServer).FindPollByKeyWord(ctx, req.(*SearchQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _DDPoll_DoAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DDPollServer).DoAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ddpoll.DDPoll/DoAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DDPollServer).DoAction(ctx, req.(*UserAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _DDPoll_JoinPollGroup_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinPollQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DDPollServer).JoinPollGroup(m, &dDPollJoinPollGroupServer{stream})
}

type DDPoll_JoinPollGroupServer interface {
	Send(*Poll) error
	grpc.ServerStream
}

type dDPollJoinPollGroupServer struct {
	grpc.ServerStream
}

func (x *dDPollJoinPollGroupServer) Send(m *Poll) error {
	return x.ServerStream.SendMsg(m)
}

func _DDPoll_EstablishClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PollStreamConfig)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DDPollServer).EstablishClientStream(m, &dDPollEstablishClientStreamServer{stream})
}

type DDPoll_EstablishClientStreamServer interface {
	Send(*Next) error
	grpc.ServerStream
}

type dDPollEstablishClientStreamServer struct {
	grpc.ServerStream
}

func (x *dDPollEstablishClientStreamServer) Send(m *Next) error {
	return x.ServerStream.SendMsg(m)
}

var _DDPoll_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ddpoll.DDPoll",
	HandlerType: (*DDPollServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindPollByKeyWord",
			Handler:    _DDPoll_FindPollByKeyWord_Handler,
		},
		{
			MethodName: "DoAction",
			Handler:    _DDPoll_DoAction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EstablishPollStream",
			Handler:       _DDPoll_EstablishPollStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "JoinPollGroup",
			Handler:       _DDPoll_JoinPollGroup_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "EstablishClientStream",
			Handler:       _DDPoll_EstablishClientStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ddpoll.proto",
}
